### ISSUE TITLE
Uncaught TypeError: DevTools.instrument is not a function

### ISSUE THREAD

**Issue by smilingpoplar** [gaearon/redux-devtools#249]
When I upgrade babel 5 to 6, I encounter this problem: 

```
Uncaught TypeError: DevTools.instrument is not a function
```

Any idea?

**Comment by gaearon** [comment]
Best guess: you do

```
var DevTools = require('../containers/DevTools')
```

but Babel 6 no longer attempts to interop with CommonJS this way.

Since you used `export default` in `DevTools.js`, you need to explicitly use the `default` export when importing:

```
var DevTools = require('../containers/DevTools').default
```

**Comment by smilingpoplar** [comment]
Exactly this problem!
thanks, @gaearon

**Comment by gaearon** [comment]
If your project mostly uses ES6 modules, I would suggest you to use the solution I offered. If it mostly uses CommonJS, use `module.exports`. It’s best to avoid mixing the two approaches.

**Comment by smilingpoplar** [comment]
ok
